### ISSUE TITLE
Upstream changed package without bumping version

### ISSUE THREAD

**Issue by cheese** [flathub/com.wps.Office#55]
wps-office_11.1.0.8865_amd64.deb
Length: 252362146
sha256sum: a8adc62d0c5245ed312d6454437c924b7760dacd5f7a71aeb5997ee85590d7c1

So, the flatpak will fail to install now.

**Comment by gasinvein** [comment]
Meeh, I wonder why they keep re-creating packages without version bumps.

@wjt @barthalion Looks like flatpak-external-data-checker didn't detect current sha256 mismatch. How frequently does it check manifests?

**Comment by barthalion** [comment]
```
2019-12-28T19:08:07.5363549Z ==> checking com.wps.Office
2019-12-28T19:08:07.8223099Z + 2019-12-28 19:08:07,821   DEBUG src.checker: Loading modules from /github/workspace/flathub/com.wps.Office/shared-modules/gtk2/gtk2.json
2019-12-28T19:08:07.8235473Z + 2019-12-28 19:08:07,822    INFO src.checker: Referenced file not found: shared-modules/gtk2/gtk2.json
2019-12-28T19:08:07.8236231Z + 2019-12-28 19:08:07,822   DEBUG src.checker: Loading modules from /github/workspace/flathub/com.wps.Office/shared-modules/qt4/qt4-4.8.7-minimal.json
2019-12-28T19:08:07.8236739Z + 2019-12-28 19:08:07,822    INFO src.checker: Referenced file not found: shared-modules/qt4/qt4-4.8.7-minimal.json
2019-12-28T19:08:07.8237208Z + 2019-12-28 19:08:07,823   DEBUG src.checker: Loading modules from /github/workspace/flathub/com.wps.Office/shared-modules/udev/udev-175.json
2019-12-28T19:08:07.8237627Z + 2019-12-28 19:08:07,823    INFO src.checker: Referenced file not found: shared-modules/udev/udev-175.json
2019-12-28T19:08:07.8245884Z + 2019-12-28 19:08:07,823   DEBUG src.checker: Loading modules from /github/workspace/flathub/com.wps.Office/shared-modules/glu/glu-9.0.0.json
2019-12-28T19:08:07.8246334Z + 2019-12-28 19:08:07,823    INFO src.checker: Referenced file not found: shared-modules/glu/glu-9.0.0.json
2019-12-28T19:08:07.8246787Z + 2019-12-28 19:08:07,823   DEBUG src.checker: Checking module wps-i18n (path: /github/workspace/flathub/com.wps.Office/com.wps.Office.yml)
2019-12-28T19:08:07.8247248Z + 2019-12-28 19:08:07,823   DEBUG src.checker: Checking module wps (path: /github/workspace/flathub/com.wps.Office/com.wps.Office.yml)
2019-12-28T19:08:07.8247688Z + 2019-12-28 19:08:07,823   DEBUG src.checker: Checking individual sources in /github/workspace/flathub/com.wps.Office/com.wps.Office.yml
2019-12-28T19:08:07.8248064Z + 2019-12-28 19:08:07,823   DEBUG src.checker: [1/1] checking wps-office.deb
2019-12-28T19:08:07.8248486Z + 2019-12-28 19:08:07,824   DEBUG src.checkers.debianrepochecker: wps-office.deb is not a debian-repo type ext data
2019-12-28T19:08:07.8248900Z + 2019-12-28 19:08:07,824   DEBUG src.checkers.flashchecker: wps-office.deb is not a flash type ext data
2019-12-28T19:08:07.8249415Z + 2019-12-28 19:08:07,824   DEBUG src.checkers.htmlchecker: Getting extra data info from https://linux.wps.com/js/meta.js; may take a while
2019-12-28T19:08:08.3080711Z + 2019-12-28 19:08:08,307   DEBUG src.checkers.htmlchecker: version-pattern re.compile('version\\s*=\\s*"([\\d.-]+)"') matched: 11.1.0.8865
2019-12-28T19:08:08.3087251Z + 2019-12-28 19:08:08,308   DEBUG src.checkers.htmlchecker: url-pattern re.compile('download_link_deb\\s*=\\s*"(http[s]?://[\\w\\d$-_@.&+]+)"') matched: http://wdl1.pcfg.cache.wpscdn.com/wpsdl/wpsoffice/download/linux/8865/wps-office_11.1.0.8865_amd64.deb
2019-12-28T19:08:08.3087822Z + 2019-12-28 19:08:08,308 WARNING src.checkers.htmlchecker: wps-office.deb had no available URL
2019-12-28T19:52:56.9017102Z + 2019-12-28 19:52:56,901    INFO src.checker: Updating /github/workspace/flathub/com.wps.Office/com.wps.Office.yml
2019-12-28T19:52:56.9133331Z CHANGE SOON: wps-office.deb
2019-12-28T19:52:56.9134064Z  Has a new version:
2019-12-28T19:52:56.9134862Z   URL:     http://wdl1.pcfg.cache.wpscdn.com/wpsdl/wpsoffice/download/linux/8865/wps-office_11.1.0.8865_amd64.deb
2019-12-28T19:52:56.9135901Z   SHA256:  a8adc62d0c5245ed312d6454437c924b7760dacd5f7a71aeb5997ee85590d7c1
2019-12-28T19:52:56.9136092Z   Size:    252362146
2019-12-28T19:52:56.9136185Z   Version: 11.1.0.8865
2019-12-28T19:52:56.9136255Z 
2019-12-28T19:52:56.9136319Z 
2019-12-28T19:52:56.9159961Z Traceback (most recent call last):
2019-12-28T19:52:56.9160525Z   File "/usr/lib/python3.7/xml/sax/expatreader.py", line 217, in feed
2019-12-28T19:52:56.9160666Z     self._parser.Parse(data, isFinal)
2019-12-28T19:52:56.9160798Z xml.parsers.expat.ExpatError: junk after document element: line 80, column 0
2019-12-28T19:52:56.9160876Z 
2019-12-28T19:52:56.9160994Z During handling of the above exception, another exception occurred:
2019-12-28T19:52:56.9161081Z 
2019-12-28T19:52:56.9161187Z Traceback (most recent call last):
2019-12-28T19:52:56.9161791Z   File "/opt/flatpak-external-data-checker/flatpak-external-data-checker", line 30, in <module>
2019-12-28T19:52:56.9161935Z     main()
2019-12-28T19:52:56.9162294Z   File "/opt/flatpak-external-data-checker/src/main.py", line 216, in main
2019-12-28T19:52:56.9162426Z     changes = manifest_checker.update_manifests()
2019-12-28T19:52:56.9163012Z   File "/opt/flatpak-external-data-checker/src/checker.py", line 262, in update_manifests
2019-12-28T19:52:56.9163867Z     self._update_manifest(path, datas, changes)
2019-12-28T19:52:56.9164329Z   File "/opt/flatpak-external-data-checker/src/checker.py", line 254, in _update_manifest
2019-12-28T19:52:56.9164476Z     add_release_to_file(appdata, last_update.version, last_update.timestamp.strftime("%F"))
2019-12-28T19:52:56.9164875Z   File "/opt/flatpak-external-data-checker/src/lib/appdata.py", line 139, in add_release_to_file
2019-12-28T19:52:56.9165185Z     add_release(appdata_path, buf, version, date)
2019-12-28T19:52:56.9165574Z   File "/opt/flatpak-external-data-checker/src/lib/appdata.py", line 134, in add_release
2019-12-28T19:52:56.9165712Z     reader.parse(in_path_or_stream)
2019-12-28T19:52:56.9165834Z   File "/usr/lib/python3.7/xml/sax/saxutils.py", line 312, in parse
2019-12-28T19:52:56.9165957Z     self._parent.parse(source)
2019-12-28T19:52:56.9166080Z   File "/usr/lib/python3.7/xml/sax/expatreader.py", line 111, in parse
2019-12-28T19:52:56.9166198Z     xmlreader.IncrementalParser.parse(self, source)
2019-12-28T19:52:56.9166330Z   File "/usr/lib/python3.7/xml/sax/xmlreader.py", line 125, in parse
2019-12-28T19:52:56.9166452Z     self.feed(buffer)
2019-12-28T19:52:56.9166571Z   File "/usr/lib/python3.7/xml/sax/expatreader.py", line 221, in feed
2019-12-28T19:52:56.9166693Z     self._err_handler.fatalError(exc)
2019-12-28T19:52:56.9166799Z   File "/usr/lib/python3.7/xml/sax/saxutils.py", line 246, in fatalError
2019-12-28T19:52:56.9166931Z     self._err_handler.fatalError(exception)
2019-12-28T19:52:56.9167053Z   File "/usr/lib/python3.7/xml/sax/handler.py", line 38, in fatalError
2019-12-28T19:52:56.9167174Z     raise exception
2019-12-28T19:52:56.9167315Z xml.sax._exceptions.SAXParseException: /github/workspace/flathub/com.wps.Office/com.wps.Office.appdata.xml:80:0: junk after document element
```

I haven't look whether it's external-data-checker bug or not yet.

**Comment by wjt** [comment]
It's not a checker bug. The file is not a valid XML document. It contains two root elements.

**Comment by gasinvein** [comment]
@wjt Huh, indeed it does. How do we handle multiple appstream components, then?

**Comment by wjt** [comment]
No idea!

(If in fact this multiple-root-element XML-like format is what the Flatpak and AppStream tools expect and understand, then I suppose the fact that the checker assumes the file is meant to be an XML document is a bug. :-) The [relevant code in the checker](https://github.com/flathub/flatpak-external-data-checker/blob/master/src/lib/appdata.py) is already pretty gnarly due to the need to preserve formatting while also actually using an XML parser…)

**Comment by gasinvein** [comment]
I guess we can just drop all components except primary. AFAIK none of current frontends supports it anyway.
